_name_or_path:
    value: allenai/unifiedqa-t5-base
_wandb:
    value:
        cli_version: 0.21.3
        e:
            mq9vbwe00p6ugrmqwge0go9odnjnvoch:
                args:
                    - --dataset
                    - rad
                    - --method
                    - Reasoning
                    - --epoch
                    - "150"
                    - --lr
                    - "5e-4"
                    - --bs
                    - "8"
                    - --source_len
                    - "512"
                    - --target_len
                    - "256"
                    - --train_text_file_path
                    - /home/mixlab/tabular/medthink/Medthink/Medthink_Dataset/R-RAD/closed-end/trainset.json
                    - --img_file_path
                    - /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/detr.pth
                    - --img_name_map
                    - /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/name_map.json
                    - --pretrained_model_path
                    - allenai/unifiedqa-t5-base
                    - --output_dir
                    - /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Reasoning
                codePath: Medthink_Code/closed_end_train.py
                codePathLocal: closed_end_train.py
                cpu_count: 16
                cpu_count_logical: 24
                cudaVersion: "12.4"
                disk:
                    /:
                        total: "1005867986944"
                        used: "136531578880"
                email: hongwonseok11@gmail.com
                executable: /workspace/.conda/envs/medthink/bin/python
                git:
                    commit: 0930f9f6152f6d3cadb13e854d913877067cfb42
                    remote: https://github.com/HongWonSeok/HONG_MedThink.git
                gpu: NVIDIA GeForce RTX 3080
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ampere
                      cudaCores: 8704
                      memoryTotal: "10737418240"
                      name: NVIDIA GeForce RTX 3080
                      uuid: GPU-0f08f27c-c8d0-0ed6-69ca-26e9af7ad36a
                host: ssh-vm-deployment-84849cddf-bdwzx
                memory:
                    total: "134795862016"
                os: Linux-5.15.0-151-generic-x86_64-with-glibc2.17
                program: closed_end_train.py
                python: CPython 3.8.20
                root: /home/mixlab/tabular/medthink/Medthink/Medthink_Code
                startedAt: "2025-09-01T13:59:27.523366Z"
                writerId: mq9vbwe00p6ugrmqwge0go9odnjnvoch
        m:
            - "1": train/global_step
              "6":
                - 3
              "7": []
            - "2": '*'
              "5": 1
              "6":
                - 1
              "7": []
        python_version: 3.8.20
        t:
            "1":
                - 1
                - 11
                - 49
                - 51
                - 100
            "2":
                - 1
                - 11
                - 49
                - 51
                - 100
            "3":
                - 7
                - 66
            "4": 3.8.20
            "5": 0.21.3
            "6": 4.28.1
            "12": 0.21.3
            "13": linux-x86_64
adafactor:
    value: false
adam_beta1:
    value: 0.9
adam_beta2:
    value: 0.999
adam_epsilon:
    value: 1e-08
add_cross_attention:
    value: false
architectures:
    value:
        - T5ForConditionalGeneration
auto_find_batch_size:
    value: false
bad_words_ids:
    value: null
begin_suppress_tokens:
    value: null
bf16:
    value: false
bf16_full_eval:
    value: false
bos_token_id:
    value: null
chunk_size_feed_forward:
    value: 0
cross_attention_hidden_size:
    value: null
d_ff:
    value: 3072
d_kv:
    value: 64
d_model:
    value: 768
data_seed:
    value: None
dataloader_drop_last:
    value: false
dataloader_num_workers:
    value: 0
dataloader_pin_memory:
    value: true
ddp_bucket_cap_mb:
    value: None
ddp_find_unused_parameters:
    value: None
ddp_timeout:
    value: 1800
debug:
    value: '[]'
decoder_start_token_id:
    value: 0
deepspeed:
    value: None
dense_act_fn:
    value: relu
disable_tqdm:
    value: false
diversity_penalty:
    value: 0
do_eval:
    value: true
do_predict:
    value: false
do_sample:
    value: false
do_train:
    value: false
dropout_rate:
    value: 0.1
early_stopping:
    value: false
encoder_no_repeat_ngram_size:
    value: 0
eos_token_id:
    value: 1
eval_accumulation_steps:
    value: None
eval_batch_size:
    value: 8
eval_delay:
    value: 0
eval_steps:
    value: None
evaluation_strategy:
    value: epoch
exponential_decay_length_penalty:
    value: null
feed_forward_proj:
    value: relu
finetuning_task:
    value: null
forced_bos_token_id:
    value: null
forced_eos_token_id:
    value: null
fp16:
    value: false
fp16_backend:
    value: auto
fp16_full_eval:
    value: false
fp16_opt_level:
    value: O1
fsdp:
    value: '[]'
fsdp_config:
    value: '{''fsdp_min_num_params'': 0, ''xla'': False, ''xla_fsdp_grad_ckpt'': False}'
fsdp_min_num_params:
    value: 0
fsdp_transformer_layer_cls_to_wrap:
    value: None
full_determinism:
    value: false
generation_config:
    value: None
generation_max_length:
    value: 256
generation_num_beams:
    value: None
gradient_accumulation_steps:
    value: 1
gradient_checkpointing:
    value: false
greater_is_better:
    value: true
group_by_length:
    value: false
half_precision_backend:
    value: auto
hub_model_id:
    value: None
hub_private_repo:
    value: false
hub_strategy:
    value: every_save
hub_token:
    value: <HUB_TOKEN>
id2label:
    value:
        "0": LABEL_0
        "1": LABEL_1
ignore_data_skip:
    value: false
include_inputs_for_metrics:
    value: false
initializer_factor:
    value: 1
is_decoder:
    value: false
is_encoder_decoder:
    value: true
is_gated_act:
    value: false
jit_mode_eval:
    value: false
label_names:
    value: None
label_smoothing_factor:
    value: 0
label2id:
    value:
        LABEL_0: 0
        LABEL_1: 1
layer_norm_epsilon:
    value: 1e-06
learning_rate:
    value: 0.0005
length_column_name:
    value: length
length_penalty:
    value: 1
load_best_model_at_end:
    value: false
local_rank:
    value: -1
log_level:
    value: passive
log_level_replica:
    value: warning
log_on_each_node:
    value: true
logging_dir:
    value: /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Reasoning/Reasoning/runs/Sep01_13-59-19_ssh-vm-deployment-84849cddf-bdwzx
logging_first_step:
    value: false
logging_nan_inf_filter:
    value: true
logging_steps:
    value: 500
logging_strategy:
    value: epoch
lr_scheduler_type:
    value: linear
max_grad_norm:
    value: 1
max_length:
    value: 20
max_steps:
    value: -1
metric_for_best_model:
    value: accuracy
min_length:
    value: 0
model_type:
    value: t5
mp_parameters:
    value: ""
n_positions:
    value: 512
no_cuda:
    value: false
no_repeat_ngram_size:
    value: 0
num_beam_groups:
    value: 1
num_beams:
    value: 1
num_decoder_layers:
    value: 12
num_heads:
    value: 12
num_layers:
    value: 12
num_return_sequences:
    value: 1
num_train_epochs:
    value: 150
optim:
    value: adamw_hf
optim_args:
    value: None
output_attentions:
    value: false
output_dir:
    value: /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Reasoning/Reasoning
output_hidden_states:
    value: false
output_past:
    value: true
output_scores:
    value: false
overwrite_output_dir:
    value: false
pad_token_id:
    value: 0
past_index:
    value: -1
per_device_eval_batch_size:
    value: 8
per_device_train_batch_size:
    value: 8
per_gpu_eval_batch_size:
    value: None
per_gpu_train_batch_size:
    value: None
predict_with_generate:
    value: true
prediction_loss_only:
    value: false
prefix:
    value: null
problem_type:
    value: null
push_to_hub:
    value: false
push_to_hub_model_id:
    value: None
push_to_hub_organization:
    value: None
push_to_hub_token:
    value: <PUSH_TO_HUB_TOKEN>
ray_scope:
    value: last
relative_attention_max_distance:
    value: 128
relative_attention_num_buckets:
    value: 32
remove_invalid_values:
    value: false
remove_unused_columns:
    value: true
repetition_penalty:
    value: 1
report_to:
    value: '[''wandb'']'
resume_from_checkpoint:
    value: None
return_dict:
    value: true
return_dict_in_generate:
    value: false
run_name:
    value: /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Reasoning/Reasoning
save_on_each_node:
    value: false
save_safetensors:
    value: false
save_steps:
    value: 500
save_strategy:
    value: "no"
save_total_limit:
    value: 1
seed:
    value: 42
sep_token_id:
    value: null
sharded_ddp:
    value: '[]'
skip_memory_metrics:
    value: true
sortish_sampler:
    value: false
suppress_tokens:
    value: null
task_specific_params:
    value:
        summarization:
            early_stopping: true
            length_penalty: 2
            max_length: 200
            min_length: 30
            no_repeat_ngram_size: 3
            num_beams: 4
            prefix: 'summarize: '
        translation_en_to_de:
            early_stopping: true
            max_length: 300
            num_beams: 4
            prefix: 'translate English to German: '
        translation_en_to_fr:
            early_stopping: true
            max_length: 300
            num_beams: 4
            prefix: 'translate English to French: '
        translation_en_to_ro:
            early_stopping: true
            max_length: 300
            num_beams: 4
            prefix: 'translate English to Romanian: '
temperature:
    value: 1
tf_legacy_loss:
    value: false
tf32:
    value: None
tie_encoder_decoder:
    value: false
tie_word_embeddings:
    value: true
tokenizer_class:
    value: null
top_k:
    value: 50
top_p:
    value: 1
torch_compile:
    value: false
torch_compile_backend:
    value: None
torch_compile_mode:
    value: None
torch_dtype:
    value: null
torchdynamo:
    value: None
torchscript:
    value: false
tpu_metrics_debug:
    value: false
tpu_num_cores:
    value: None
train_batch_size:
    value: 8
transformers_version:
    value: 4.28.1
typical_p:
    value: 1
use_bfloat16:
    value: false
use_cache:
    value: true
use_ipex:
    value: false
use_legacy_prediction_loop:
    value: false
use_mps_device:
    value: false
vocab_size:
    value: 32128
warmup_ratio:
    value: 0
warmup_steps:
    value: 0
weight_decay:
    value: 0.01
xpu_backend:
    value: None
