
# Explaination learnable prompt
CUDA_VISIBLE_DEVICES=0 python closed_end_generate.py --LP_use --dataset rad --method Explanation --eval_bs 8 --learnable_prompt_len 10 --source_len 502 --target_len 256 --text_file_path /home/mixlab/tabular/medthink/Medthink/Medthink_Dataset/R-RAD/closed-end/testset.json --model_path /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Explanation/learnable_prompt/Explanation --img_file_path /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/detr.pth --img_name_map  /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/name_map.json --output_dir /home/mixlab/tabular/medthink/output/rad_closed_end_generate/Explanation/First/LP_10
# CUDA_VISIBLE_DEVICES=0,1,2,3 python closed_end_generate.py --LP_use --dataset rad --method Explanation --eval_bs 8 --lp_len 10 --source_len 502 --target_len 256 --text_file_path /home/mixlab/tabular/medthink/Medthink/Medthink_Dataset/R-RAD/closed-end/testset.json --model_path /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Explanation/learnable_prompt/Explanation --img_file_path /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/detr.pth --img_name_map  /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/name_map.json --output_dir /home/mixlab/tabular/medthink/output/rad_closed_end_generate/Explanation/First/LP_10

# Reasoning


# CUDA_VISIBLE_DEVICES=0,1,2,3 python closed_end_generate.py --dataset rad --method Reasoning --eval_bs 8 --source_len 512 --target_len 256 --text_file_path /home/mixlab/tabular/medthink/Medthink/Medthink_Dataset/R-RAD/closed-end/trainset.json --model_path /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Reasoning/First/acc --img_file_path /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/detr.pth --img_name_map /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/name_map.json --output_dir /home/mixlab/tabular/medthink/output/rad_closed_end_generate/Reasoning/First
# CUDA_VISIBLE_DEVICES=0,1,2,3 python closed_end_generate.py --dataset rad --method Reasoning --eval_bs 8 --source_len 512 --target_len 256 --text_file_path /home/mixlab/tabular/medthink/Medthink/Medthink_Dataset/R-RAD/closed-end/testset.json --model_path /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Reasoning/First/acc --img_file_path /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/detr.pth --img_name_map /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/name_map.json --output_dir /home/mixlab/tabular/medthink/output/rad_closed_end_generate/Reasoning/First

# Explanation

# CUDA_VISIBLE_DEVICES=0,1,2,3 python closed_end_generate.py --dataset rad --method Explanation --eval_bs 8 --source_len 512 --target_len 256 --text_file_path /home/mixlab/tabular/medthink/Medthink/Medthink_Dataset/R-RAD/closed-end/testset.json --model_path /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Explanation/First --img_file_path /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/detr.pth --img_name_map  /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/name_map.json --output_dir /home/mixlab/tabular/medthink/output/rad_closed_end_generate/Explanation/First
# CUDA_VISIBLE_DEVICES=0,1,2,3 python closed_end_generate.py --dataset rad --method Explanation --eval_bs 8 --source_len 512 --target_len 256 --text_file_path /home/mixlab/tabular/medthink/Medthink/Medthink_Dataset/R-RAD/closed-end/trainset.json --model_path /home/mixlab/tabular/medthink/output/rad_closed_end_experiments/Explanation/First --img_file_path /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/detr.pth --img_name_map  /home/mixlab/tabular/medthink/data/R-RAD/visual_encoder/name_map.json --output_dir /home/mixlab/tabular/medthink/output/rad_closed_end_generate/Explanation/First